In [ ]:
df = df.drop(['botanist', 'plant_id', 'scientific_name','error'], axis=1)

In [ ]:
df = df.drop(['botanist', 'plant_id', 'scientific_name','error'], axis=1)

In [ ]:
def split_names(x):
    '''split first and last names'''

    if isinstance(x, dict):
        # print(x['name'], len(x['name'].split(' ')))
        return x['name'].split(' ')
    else:
        return [None, None]

In [ ]:
df['first_name'] = df['botanist'].apply(split_names).apply(lambda x: x[0])
df['last_name'] = df['botanist'].apply(split_names).apply(lambda x: x[1])

In [ ]:
df['email'] = df['botanist'].str['email']

In [ ]:
df = df.drop('images', axis=1)

In [ ]:
df['recording_taken'] = pd.to_datetime(df['recording_taken'])

In [ ]:
df['last_watered'] = pd.to_datetime(df['last_watered'])

In [ ]:
# rename origin local
df = df.rename(columns={'origin_location': 'origin_country'})

In [ ]:
df['error'][df['error'].notnull()]

In [ ]:
df['origin_country'] = df['origin_country'].str[3]

In [ ]:
df['origin_continent'] = df['origin_country'].replace(continents)

In [ ]:
df['origin_country'] = df['origin_country'].replace(countries)

In [54]:
df = df.drop(['botanist', 'plant_id', 'scientific_name','error'], axis=1)

In [55]:
df

,cycle,last_watered,name,origin_country,recording_taken,soil_moisture,sunlight,temperature,error,first_name,last_name,email,origin_continent
0,Perennial,2023-05-08 14:03:04,Epipremnum Aureum,Brazil,2023-05-09 13:47:22,17.271524,[Part shade],13.218322,NaN,Carl,Linnaeus,carl.linnaeus@lnhm.co.uk,SA
1,NaN,2023-05-08 13:54:32,Venus flytrap,United States,2023-05-09 13:47:23,15.382257,NaN,12.056447,NaN,Gertrude,Jekyll,gertrude.jekyll@lnhm.co.uk,NA
2,NaN,2023-05-08 14:10:54,Corpse flower,Nigeria,2023-05-09 13:47:24,22.665490,NaN,9.196276,NaN,Carl,Linnaeus,carl.linnaeus@lnhm.co.uk,AF
3,NaN,2023-05-08 14:50:16,Rafflesia arnoldii,Brazil,2023-05-09 13:47:25,20.624562,NaN,10.049522,NaN,Eliza,Andrews,eliza.andrews@lnhm.co.uk,SA
4,NaN,2023-05-09 13:16:25,Black bat flower,El Salvador,2023-05-09 13:47:26,98.149238,NaN,11.358941,NaN,Carl,Linnaeus,carl.linnaeus@lnhm.co.uk,NA
5,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,plant sensor fault,None,None,NaN,NaN
6,Perennial,2023-05-09 13:35:35,Wollemi pine,Canada,2023-05-09 13:47:28,99.338990,[Part shade],10.998294,NaN,Eliza,Andrews,eliza.andrews@lnhm.co.uk,NA
7,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,plant not found,None,None,NaN,NaN
8,Herbaceous Perennial,2023-05-09 13:23:01,Bird of paradise,Ivory Coast,2023-05-09 13:47:29,98.540212,"[Full sun, part shade]",11.586268,NaN,Eliza,Andrews,eliza.andrews@lnhm.co.uk,AF
9,Perennial,2023-05-08 14:12:43,Cactus,Germany,2023-05-09 13:47:30,17.983031,"[Full sun, part shade]",10.630175,NaN,Gertrude,Jekyll,gertrude.jekyll@lnhm.co.uk,EU
10,NaN,2023-05-09 13:04:57,"Dragon tree,",Croatia,2023-05-09 13:47:31,97.536421,NaN,13.976671,NaN,Gertrude,Jekyll,gertrude.jekyll@lnhm.co.uk,EU
11,Herbaceous Perennial,2023-05-09 13:37:24,Asclepias Curassavica,United States,2023-05-09 13:47:32,99.429940,[Full sun],9.506140,NaN,Gertrude,Jekyll,gertrude.jekyll@lnhm.co.uk,NA
12,NaN,2023-05-09 13:13:51,Brugmansia X Candida,United States,2023-05-09 13:47:33,98.012870,NaN,12.872636,NaN,Eliza,Andrews,eliza.andrews@lnhm.co.uk,NA
13,NaN,NaT,NaN,NaN,NaT,NaN,NaN,NaN,plant sensor fault,None,None,NaN,NaN